name:  my-first-github-actions-workflow
on: [push]
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
      
